# Generated by Django 3.2.4 on 2021-07-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.TextField(default='This awesome product'),
        ),
    ]
