# Generated by Django 3.2.4 on 2021-07-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsapp', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Jagmohan', max_length=50),
        ),
    ]
